-- =====================================================================
-- Source : CPDQ999.CPDQ_MLC_PFG_SAP_NE_PG1 (PROCEDURE)
-- Target : PostgreSQL 1 function(s)
-- Generated by ora2pg_tool - REVIEW BEFORE DEPLOYING
-- =====================================================================

-- ---------------------------------------------------------------------
-- TODO[REVIEW] - automatic conversion could not guarantee these:
--   [ERROR] COMMIT commented out - a PostgreSQL function runs inside the caller's transaction. Move the transaction control to the caller, or convert this object to a PROCEDURE.
--            at: COMMIT
--   [WARN] Oracle optimizer hint is inert in PostgreSQL - remove it or install pg_hint_plan.
--            at: /*+
-- ---------------------------------------------------------------------

-- CPDQ999.CPDQ_MLC_PFG_SAP_NE_PG1  ->  cpdq999.cpdq_mlc_pfg_sap_ne_pg1
CREATE OR REPLACE FUNCTION cpdq999.cpdq_mlc_pfg_sap_ne_pg1(
    IN lifecyclecode text,
    IN queryid integer,
    OUT returncode integer)
RETURNS integer
LANGUAGE 'plpgsql'
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    schemaname text := 'CPDQ999';
    procname text := 'cpdq_mlc_pfg_sap_ne_pg1';
    severity integer := 2;
    lineid integer := 0;
    selectcur CURSOR FOR SELECT /*+ use_hash(m, x) */
                m.code,
                mn.name,
                'SAP PFG Code Does Not Agree With PGINet' AS message,
                m.material_status_code,
                m.material_type_code,
                ms.sale_organization_code || ' / ' || ms.distribution_channel_code AS sale_org,
                p.globe_code AS plant_id,
                p.name AS plant_name,
                gsm.rcprc AS sap_pfg,
                rel.item_grp_c AS pgi_pfg
              FROM v_material m,
                   v_material_name mn,
                   v_material_sale ms,
                   glb_rgtt_mfor gsm,
                   v_plant p,
                   nppc_globe_material_xref x,
                   packaged_good_item_grp_rel rel
             WHERE m.deletion_date IS NULL
               AND m.mat_rec_owner_code = 'US'
               AND m.material_status_code IN ('Z2', 'Z3')
               AND coalesce(ms.mat_sale_status_code, ' ') IN (' ', 'ZX')
               AND (m.code)::numeric NOT IN (SELECT DISTINCT (exception_id)::numeric
                                               FROM report_exception
                                              WHERE report_id = 'CPDQ_MLC_PFG_SAP_NE_PG1')
               AND m.code = mn.material_code
               AND mn.deletion_date IS NULL
               AND ms.sale_organization_code IN ('US53')
               AND ms.material_code = m.material_code
               AND ms.deletion_date IS NULL
               AND mn.language_code = 'E'
               AND ms.material_code = gsm.matnr
               AND gsm.werks = p.globe_code
               AND p.deletion_date IS NULL
               AND p.company_code = 'US29'
               AND (mn.material_code)::numeric = x.globe_material_n
               AND x.nppc_id = rel.item_id
               AND rel.item_grp_id = x.item_grp_id
               AND rel.item_grp_c != gsm.rcprc
             ORDER BY m.code, sale_org;
    -- Main body of procedure
    v_sqlstate text;
    v_message  text;
    v_detail   text;
    v_hint     text;
    v_context  text;
BEGIN
    FOR scur IN selectcur LOOP
        lineid := lineid + 1;

        BEGIN

            INSERT INTO cpdq.procedure_line (
                stored_procedure_id,
                line_id,
                lifecycle_c,
                report_line_c,
                severity_n,
                report_description_x,
                message_x,
                processed_c)
            VALUES (
                queryid,
                lineid,
                left(lifecyclecode, 4),
                left(scur.code, 20),
                severity,
                left(scur.name, 80),
                left(scur.message, 4000),
                NULL
            );

        EXCEPTION
            WHEN OTHERS THEN
                GET STACKED DIAGNOSTICS
                    v_sqlstate = RETURNED_SQLSTATE,
                    v_message  = MESSAGE_TEXT,
                    v_detail   = PG_EXCEPTION_DETAIL,
                    v_hint     = PG_EXCEPTION_HINT,
                    v_context  = PG_EXCEPTION_CONTEXT;

                PERFORM cpdc999.rmdpk_error_log_util_log_error
                (
                    schemaname,
                    procname,
                    'Inserting report lines',
                    left
                    (
                        concat_ws
                        (
                            ' | ',
                            'Error while trying to insert data for material ' || scur.code ||
                            ' into PROCEDURE_LINE table',
                            nullif(v_detail, ''),
                            nullif(v_hint, ''),
                            nullif(v_context, '')
                        ),
                        2000
                    ),
                    v_sqlstate,
                    left
                    (
                        coalesce
                        (
                            nullif(v_message, ''),
                            'Unknown PostgreSQL error'
                        ),
                        1000
                    )
                );
                returncode := -1;
                RETURN;
        END;

        BEGIN

            IF cpdq999.cpdq_data_quality_query_pkg_store_one_column_detail(
                            1,
                            scur.material_type_code,
                            scur.code,
                            queryid,
                            lineid) != 0 THEN
                returncode := -2;
                RETURN;
            END IF;

            IF cpdq999.cpdq_data_quality_query_pkg_store_one_column_detail(
                            1 + 1,
                            scur.material_status_code,
                            scur.code,
                            queryid,
                            lineid) != 0 THEN
                returncode := -3;
                RETURN;
            END IF;

            IF cpdq999.cpdq_data_quality_query_pkg_store_one_column_detail(
                            1 + 2,
                            scur.plant_id,
                            scur.code,
                            queryid,
                            lineid) != 0 THEN
                returncode := -4;
                RETURN;
            END IF;

            IF cpdq999.cpdq_data_quality_query_pkg_store_one_column_detail(
                            1 + 3,
                            scur.plant_name,
                            scur.code,
                            queryid,
                            lineid) != 0 THEN
                returncode := -5;
                RETURN;
            END IF;

            IF cpdq999.cpdq_data_quality_query_pkg_store_one_column_detail(
                            1 + 4,
                            scur.sap_pfg,
                            scur.code,
                            queryid,
                            lineid) != 0 THEN
                returncode := -6;
                RETURN;
            END IF;

            IF cpdq999.cpdq_data_quality_query_pkg_store_one_column_detail(
                            1 + 5,
                            scur.pgi_pfg,
                            scur.code,
                            queryid,
                            lineid) != 0 THEN
                returncode := -7;
                RETURN;
            END IF;

        EXCEPTION
            WHEN OTHERS THEN
                GET STACKED DIAGNOSTICS
                    v_sqlstate = RETURNED_SQLSTATE,
                    v_message  = MESSAGE_TEXT,
                    v_detail   = PG_EXCEPTION_DETAIL,
                    v_hint     = PG_EXCEPTION_HINT,
                    v_context  = PG_EXCEPTION_CONTEXT;

                PERFORM cpdc999.rmdpk_error_log_util_log_error
                (
                    schemaname,
                    procname,
                    'Inserting report lines',
                    left
                    (
                        concat_ws
                        (
                            ' | ',
                            'Error while trying to insert data for material ' || scur.code ||
                            ' into PROCEDURE_LINE_COLUMN table',
                            nullif(v_detail, ''),
                            nullif(v_hint, ''),
                            nullif(v_context, '')
                        ),
                        2000
                    ),
                    v_sqlstate,
                    left
                    (
                        coalesce
                        (
                            nullif(v_message, ''),
                            'Unknown PostgreSQL error'
                        ),
                        1000
                    )
                );
                returncode := -20;
                RETURN;
        END;

    END LOOP;

    -- TODO[REVIEW] commit;

    returncode := 0;

EXCEPTION
    WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS
            v_sqlstate = RETURNED_SQLSTATE,
            v_message  = MESSAGE_TEXT,
            v_detail   = PG_EXCEPTION_DETAIL,
            v_hint     = PG_EXCEPTION_HINT,
            v_context  = PG_EXCEPTION_CONTEXT;

        PERFORM cpdc999.rmdpk_error_log_util_log_error
        (
            schemaname,
            procname,
            'Top level exception',
            left
            (
                concat_ws
                (
                    ' | ',
                    'Error not caught by exception handling in main loop.',
                    nullif(v_detail, ''),
                    nullif(v_hint, ''),
                    nullif(v_context, '')
                ),
                2000
            ),
            v_sqlstate,
            left
            (
                coalesce
                (
                    nullif(v_message, ''),
                    'Unknown PostgreSQL error'
                ),
                1000
            )
        );
        returncode := -30;
END;
$BODY$;

